### ISSUE TITLE
Rightclick Bug

### ISSUE THREAD

**Issue by Kosyne** [Ferdzz/PlaceableItems#11]
When enabled, all actions requiring a rightclick require me to be looking at a block for them to work correctly. This means I cannot eat, fire a bow, etc, unless I'm looking at an in-range block.

An error is thrown, but I do not have the exact error on me, but it listed all of the rightclick event listeners, and about an exception being thrown. The exception did not mention this plugin specifically though, I don't believe.

Here are the plugins the server is running, alongside PlaceableItems: http://i.imgur.com/W5UxrpJ.png

MC 1.11, Forge 2199

**Comment by Ferdzz** [comment]
Can you please send the full log when you get your hands on them?

**Comment by Kosyne** [comment]
Alright, got it. Note, this occurs on ANY right click when you are not within range of (the black square outline).

```
[12:59:04] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@1688f86c:
java.lang.NullPointerException
        at net.minecraft.util.math.BlockPos.func_177967_a(SourceFile:158) ~[co.class:?]
        at net.minecraft.util.math.BlockPos.func_177972_a(SourceFile:150) ~[co.class:?]
        at me.ferdz.placeableitems.event.RightClickHandler.onItemRightClick(RightClickHandler.java:27) ~[RightClickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_RightClickHandler_onItemRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:793) [SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:439) [SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) [SpongeImpl.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:408) [SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:398) [SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:222) [PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:87) [PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjb000(SourceFile:39) [fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[12:59:05] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[12:59:05] [Server thread/ERROR] [FML]: 0: HIGH
[12:59:05] [Server thread/ERROR] [FML]: 1: ASM: me.ferdz.placeableitems.event.RightClickHandler@45737efb onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 2: NORMAL
[12:59:05] [Server thread/ERROR] [FML]: 3: ASM: biomesoplenty.common.handler.GrassPathEventHandler@461dcf2e onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 4: ASM: cavern.handler.CaveEventHooks@6b3cf046 onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 5: ASM: com.pau101.fairylights.server.ServerEventHandler@f60e448 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 6: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@8f4c5bf playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 7: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@33c0778b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:59:05] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at net.minecraft.util.math.BlockPos.func_177967_a(SourceFile:158) ~[co.class:?]
        at net.minecraft.util.math.BlockPos.func_177972_a(SourceFile:150) ~[co.class:?]
        at me.ferdz.placeableitems.event.RightClickHandler.onItemRightClick(RightClickHandler.java:27) ~[RightClickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_RightClickHandler_onItemRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) ~[EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:793) ~[SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:439) ~[SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) ~[SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) ~[SpongeImpl.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:408) ~[SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:398) ~[SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:222) ~[PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:87) ~[PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjb000(SourceFile:39) ~[fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[12:59:05] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@7b56f137:
java.lang.NullPointerException
        at net.minecraft.util.math.BlockPos.func_177967_a(SourceFile:158) ~[co.class:?]
        at net.minecraft.util.math.BlockPos.func_177972_a(SourceFile:150) ~[co.class:?]
        at me.ferdz.placeableitems.event.RightClickHandler.onItemRightClick(RightClickHandler.java:27) ~[RightClickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_RightClickHandler_onItemRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:800) [SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:439) [SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) [SpongeImpl.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:408) [SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:398) [SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:222) [PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:87) [PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjb000(SourceFile:39) [fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[12:59:05] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[12:59:05] [Server thread/ERROR] [FML]: 0: HIGH
[12:59:05] [Server thread/ERROR] [FML]: 1: ASM: me.ferdz.placeableitems.event.RightClickHandler@45737efb onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 2: NORMAL
[12:59:05] [Server thread/ERROR] [FML]: 3: ASM: biomesoplenty.common.handler.GrassPathEventHandler@461dcf2e onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 4: ASM: cavern.handler.CaveEventHooks@6b3cf046 onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 5: ASM: com.pau101.fairylights.server.ServerEventHandler@f60e448 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 6: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@8f4c5bf playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[12:59:05] [Server thread/ERROR] [FML]: 7: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@33c0778b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:59:05] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at net.minecraft.util.math.BlockPos.func_177967_a(SourceFile:158) ~[co.class:?]
        at net.minecraft.util.math.BlockPos.func_177972_a(SourceFile:150) ~[co.class:?]
        at me.ferdz.placeableitems.event.RightClickHandler.onItemRightClick(RightClickHandler.java:27) ~[RightClickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_RightClickHandler_onItemRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) ~[EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:800) ~[SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:439) ~[SpongeForgeEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) ~[SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) ~[SpongeImpl.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:408) ~[SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:398) ~[SpongeCommonEventFactory.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:222) ~[PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:87) ~[PacketUtil.class:1.11-2195-6.0.0-BETA-2004]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjb000(SourceFile:39) ~[fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by Ferdzz** [comment]
Got it, I'll be checking into that. Thanks for reporting

**Comment by Xenaoo** [comment]
This bug is caused by a problem between Placeable Items and SpongeForge.

I had the same problem , and i had to remove Placeable Item for work..

**Comment by Ferdzz** [comment]
Okay, I'll see what I can do about SpongeForge

**Comment by Ferdzz** [comment]
Related to https://github.com/SpongePowered/SpongeForge/issues/1199
