### ISSUE TITLE
Big bug.

### ISSUE THREAD

**Issue by Swordzofgodz** [Ferdzz/PlaceableItems#19]
I dont know why, I have good processors and free space

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/9/17 7:16 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.newNode(Unknown Source)
	at java.util.HashMap.putVal(Unknown Source)
	at java.util.HashMap.putMapEntries(Unknown Source)
	at java.util.HashMap.<init>(Unknown Source)
	at com.google.common.collect.Maps.newHashMap(Maps.java:230)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.retexture(ModelLoader.java:620)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.retexture(ModelLoader.java:434)
	at net.minecraftforge.client.model.ModelProcessingHelper.retexture(ModelProcessingHelper.java:30)
	at net.minecraftforge.client.model.BlockStateLoader$ForgeVariant.runModelHooks(BlockStateLoader.java:172)
	at net.minecraftforge.client.model.BlockStateLoader$ForgeVariant.process(BlockStateLoader.java:191)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:757)
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1186)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:242)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153)
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:230)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.HashMap.newNode(Unknown Source)
	at java.util.HashMap.putVal(Unknown Source)
	at java.util.HashMap.putMapEntries(Unknown Source)
	at java.util.HashMap.<init>(Unknown Source)
	at com.google.common.collect.Maps.newHashMap(Maps.java:230)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.retexture(ModelLoader.java:620)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.retexture(ModelLoader.java:434)
	at net.minecraftforge.client.model.ModelProcessingHelper.retexture(ModelProcessingHelper.java:30)
	at net.minecraftforge.client.model.BlockStateLoader$ForgeVariant.runModelHooks(BlockStateLoader.java:172)
	at net.minecraftforge.client.model.BlockStateLoader$ForgeVariant.process(BlockStateLoader.java:191)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:757)
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1186)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:242)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153)
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:230)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 233376 bytes (0 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.1.2199 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2199.jar) 
	UCHIJA	forge{13.19.1.2199} [Minecraft Forge] (forge-1.11-13.19.1.2199.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJA	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.49' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.11-forge1.11-13.19.1.2199
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.49, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Phenom(tm) II X4 955 Processor

**Comment by Ferdzz** [comment]
You're only allowing 500mb of RAM to Minecraft. To run Placeable Items, you need a minimal amount of 1gb. Please see this link for info on how to raise it: http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/tutorials-and-faqs/1871637-tutorial-allocate-more-memory-for-minecraft

**Comment by Swordzofgodz** [comment]
No siree, But i will change it. Thank you

**Comment by Ferdzz** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2721696-placeable-items?comment=38
Guess that was just a coincidence that that guys name is Swordz too with the same error then ;)

Anyways, let me know if it works so I can close this issue

**Comment by Ferdzz** [comment]
I'm going to assume this was fixed. Feel free to contact me again if you experience more problems
