### ISSUE TITLE
Players can´t eat

### ISSUE THREAD

**Issue by L31H4** [Ferdzz/PlaceableItems#20]
Hello,
I´m not sure if this is the right place for my problem.
After installing your mod on server players often can´t eat. The character is doing the eating animation but the bread or what else doesnt disappers. After some tries the character maybe eats the meal. I have following messages on the concole:

[13:28:34] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@205c2ceb:
java.lang.NullPointerException
[m> 
[13:28:34] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[m> 
[13:28:34] [Server thread/ERROR] [FML]: 0: HIGH
[m> 
[13:28:34] [Server thread/ERROR] [FML]: 1: ASM: me.ferdz.placeableitems.event.RightClickHandler@78dfc7f2 onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[m> 
[13:28:34] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException

I´m using spongeforge for 1.11, forge build 2195, spongeforge build 2004
and a list of all plugins used: CommandBooks, DynMap, EconomyLite, LuckyPerms, Holograms, Keys, RedProtection, PlayerShopsRPG, Nucleus, ProjectPortals, WalletDrop, NPC´s, Sleepvote, Worldedit.

**Comment by Ferdzz** [comment]
Yes, this is the right place for bug reports.

Interesting, what is your Placeable Items version? When you say 'can't eat', do you mean that they can't eat the placed items or that they can't eat food like they would normally?

**Comment by L31H4** [comment]
They can´t eat food like they would normally do. After the eating animation is over, nothing happened.
I´m using version 3.0.3.1 for MC 1.11, i got it via curseforge.

**Comment by Ferdzz** [comment]
Alright, thank you for the report. I will be looking into it soon

**Comment by Ferdzz** [comment]
@L31H4 After testing with Forge 13.20.0.2282 and Sponge 1.11.2-2227 I was unable to reproduce the issue. Make sure you update Sponge to the latest version and tell me if the issue still happens

**Comment by Ferdzz** [comment]
No response in over a month, I'm assuming the issue is fixed. If it's not, please open a new issue.
