### ISSUE TITLE
Stuck on Mojang Screen

### ISSUE THREAD

**Issue by Lauren5224** [Ferdzz/PlaceableItems#22]
I'm playing 1.10.2 and whenever I add the mod, minecraft opens but its stuck on the Mojang screen. I thought maybe it was loading but its been loading for 10 mins now. I tried versions 3.0.4, 3.0.3.1 and 3.0.1 (ended up crashing). Maybe i'm doing something wrong?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic-Mod-Lite-1.10.2.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/20/17 3:07 PM
XRay version: 48
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_188539_a(TextureAtlasSprite.java:354)
	at net.minecraft.client.renderer.texture.TextureMap.func_184397_a(TextureMap.java:471)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:341)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:154)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:291)
	at com.mumfrey.liteloader.client.ClientProxy.onStartupComplete(ClientProxy.java:55)
	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzg000(Minecraft.java:46)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:555)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_188539_a(TextureAtlasSprite.java:354)
	at net.minecraft.client.renderer.texture.TextureMap.func_184397_a(TextureMap.java:471)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:341)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:154)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:291)
	at com.mumfrey.liteloader.client.ClientProxy.onStartupComplete(ClientProxy.java:55)
	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzg000(Minecraft.java:46)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:555)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12.4
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5658384 bytes (5 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M -Xms256M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_D6 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJA	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCHIJA	backpacks16840{3.1.5} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.5.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	thedragonlib{1.10.2-1.3.1} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.1.jar) 
	UCHIJA	armorplus{1.10.2-8.5.3.4} [ArmorPlus] (armorplus-1.10.2-8.5.3.4.jar) 
	UCHIJA	blockarmor{2.3} [Block Armor] (BlockArmor-1.10.2-2.3.jar) 
	UCHIJA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJA	craftablenametags{1.4} [Craftable Name Tags] (Craftable-Nametags-1.10.2.jar) 
	UCHIJA	craftablehorsearmour{1.2} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmor-1.3.0-1.10.jar) 
	UCHIJA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJA	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	UCHIJA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJA	lucky{7.3.0} [Lucky Block] (LuckyBlock_1-10-2_v7-3-0.zip) 
	UCHIJA	malisiscore{1.10.2-4.3.0} [MalisisCore] (malisiscore-1.10.2-4.3.0.jar) 
	UCHIJA	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0 (1).jar) 
	UCHIJA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJA	mobamputation{6.0.0} [MobAmputation] (MobAmputation-1.10.2-6.0.0.jar) 
	UCHIJA	mtm{1.9.4} [More Tools Mod] (MoreToolsMod(1.9.41.10)-6.0.jar) 
	UCHIJA	placeableitems{3.0.1} [Placeable Items Mod] (placeableitems-3.0.1.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic-Mod-Lite-1.10.2.jar)
  com.creativemd.itemphysic.ItemTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
  brad16840.common.asm.ClassTransformer
	Launched Version: 1.10.2
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.24.45, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Velvet Dreams 1.0.4 by CowedOffACliff.zip, Faithful 1.10.2-r4 5.21.41 PM.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.24.45
	OpenGlRenderer: Intel HD Graphics 5000 OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by Ferdzz** [comment]
Hi @Lauren5224 ,

The problem you're experiencing is due to a lack of ram given to Minecraft. Because of the size of the mod, you need to give at least *2 GB* of memory. You can see how to do this [here](https://youtu.be/qjUoFAmb4jA)

**Comment by Lauren5224** [comment]
Ok, I see. Thanks!

**Comment by Ferdzz** [comment]
Due to inactivity, I will close this issue. However, if you still have any problems feel free to comment on this issue again or open a new one
